import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"
import HomePage from "../components/Home"
import Footer from "../components/Footer"
import Skill from "../components/Skill"
import About from "../components/About"
import Project from "../components/Project"
export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {/*Home Section*/}
      <div className="home-container">
        <video src="home.mp4"  autoPlay muted loop>
        </video>
        <Header/>
        <HomePage/>
      </div>
    {/*About Section*/}
      <div className="about-skill-container bg-custom-gray py-10">
        <h1 className="text-gray-800 text-center">ABOUT</h1>
        <div className="flex flex-col sm:flex-row">
          <About/>
          <Skill/>
        </div>
      </div>
    {/*Project Section*/}
      <div className="project-container bg-gray-100 py-10">
        <h1 className="text-gray-800 text-center">PROJECTS</h1>
        <Project/>
      </div>
    {/*Footer Section*/}
      <Footer/>
    </div>
  )
}
