import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"
import HomePage from "../components/Home"
import Footer from "../components/Footer"
import Skill from "../components/Skill"
import About from "../components/About"
export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home-container">
        <video src="home.mp4"  autoPlay muted loop>
        </video>
        <Header/>
        <HomePage/>
      </div>
      
      <About/>
      <Skill/>
      <Footer/>
    </div>
  )
}
